POST http://localhost:5000/skills
Accept: application/json
Content-Type: application/json


{
  "name": "Apache Airflow",
  "description": "Airflow is a platform created by the community to programmatically author, schedule and monitor workflows."
}

###

GET http://localhost:5000/items
Accept: application/json
Content-Type: application/json

###

GET http://localhost:5000/items/6162ee1a5d04a8e8b2033669
Accept: application/json
Content-Type: application/json

